### ISSUE TITLE
About an asking about DT-Tests

### ISSUE THREAD

**Issue by jhernancanom** [MJindrova/dtclass#1]
Hello, friends.
I would like some one can explained me about the inconsistences that I have showed in the attached image.

I have run the basic tests, but I need to understand the following cases:

1. Why the "**Format**" is **9999#99#99** if German dates start with days? I think it should be **99#99#9999**.

2. The Monday of this week is 19 (nineteen), but the test says it is 18 (eighteen).

3. If we consider in "String Type" the values 0, 3 and 6 are correct, why for "Date Types" are the same (0, 3 and 6) if the dates have the point-separator?

Thanks. 

![image](https://user-images.githubusercontent.com/5818845/115944146-9ef84180-a479-11eb-8059-8b83ff6930a3.png)

**Comment by MJindrova** [comment]
1) It's  a format string for "Short Date" - see to API GetLocaleInfo() and  LOCALE_SSHORTDATE. 
2) It's a bug - fixed (you have fdow=1). 
3) Because you can't use SelStart and SelLength for date/datetime data type. But if you put date to textbox (textbox.Value=DATE()), then Text property contains formated string value. SelStart=0 and SelLength=2 VFP mean first and second charaters.
